// Code generated by MockGen. DO NOT EDIT.
// Source: internal/fileserver/fileserver.go
//
// Generated by this command:
//
//	mockgen -source=internal/fileserver/fileserver.go -destination internal/fileservermock/fileservermock.go -package fileservermock
//

// Package fileservermock is a generated GoMock package.
package fileservermock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileServerInterface is a mock of FileServerInterface interface.
type MockFileServerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileServerInterfaceMockRecorder
	isgomock struct{}
}

// MockFileServerInterfaceMockRecorder is the mock recorder for MockFileServerInterface.
type MockFileServerInterfaceMockRecorder struct {
	mock *MockFileServerInterface
}

// NewMockFileServerInterface creates a new mock instance.
func NewMockFileServerInterface(ctrl *gomock.Controller) *MockFileServerInterface {
	mock := &MockFileServerInterface{ctrl: ctrl}
	mock.recorder = &MockFileServerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileServerInterface) EXPECT() *MockFileServerInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileServerInterface) Delete(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileServerInterfaceMockRecorder) Delete(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileServerInterface)(nil).Delete), path)
}

// Exists mocks base method.
func (m *MockFileServerInterface) Exists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFileServerInterfaceMockRecorder) Exists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFileServerInterface)(nil).Exists), path)
}

// FileURL mocks base method.
func (m *MockFileServerInterface) FileURL(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileURL", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// FileURL indicates an expected call of FileURL.
func (mr *MockFileServerInterfaceMockRecorder) FileURL(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileURL", reflect.TypeOf((*MockFileServerInterface)(nil).FileURL), path)
}

// Write mocks base method.
func (m *MockFileServerInterface) Write(path string, data []byte) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", path, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Write indicates an expected call of Write.
func (mr *MockFileServerInterfaceMockRecorder) Write(path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFileServerInterface)(nil).Write), path, data)
}
