version: "2"

formatters:
  enable:
    - goimports
    - gofmt

linters:
  exclusions:
    paths:
      - docs/
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - unused
    - embeddedstructfieldcheck
    - errchkjson
    - errname
    - errorlint
    - godot
    - unconvert
    - reassign
    - misspell
    - mnd
    - lll
    - iotamixing
    - loggercheck
    - musttag
