// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const bulkUpdateRecipeIngredients = `-- name: BulkUpdateRecipeIngredients :batchexec
UPDATE
  recipe_ingredients
SET
  quantity = $2,
  unit = $3,
  name = $4,
  image_url = $5
WHERE
  id = $1
`

type BulkUpdateRecipeIngredientsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BulkUpdateRecipeIngredientsParams struct {
	ID       int64
	Quantity pgtype.Float4
	Unit     pgtype.Text
	Name     pgtype.Text
	ImageUrl pgtype.Text
}

func (q *Queries) BulkUpdateRecipeIngredients(ctx context.Context, arg []BulkUpdateRecipeIngredientsParams) *BulkUpdateRecipeIngredientsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Quantity,
			a.Unit,
			a.Name,
			a.ImageUrl,
		}
		batch.Queue(bulkUpdateRecipeIngredients, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BulkUpdateRecipeIngredientsBatchResults{br, len(arg), false}
}

func (b *BulkUpdateRecipeIngredientsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BulkUpdateRecipeIngredientsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const bulkUpdateRecipeSteps = `-- name: BulkUpdateRecipeSteps :batchexec
UPDATE
  recipe_steps
SET
  instruction = $2,
  image_url = $3
WHERE
  id = $1
`

type BulkUpdateRecipeStepsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BulkUpdateRecipeStepsParams struct {
	ID          int64
	Instruction pgtype.Text
	ImageUrl    pgtype.Text
}

func (q *Queries) BulkUpdateRecipeSteps(ctx context.Context, arg []BulkUpdateRecipeStepsParams) *BulkUpdateRecipeStepsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Instruction,
			a.ImageUrl,
		}
		batch.Queue(bulkUpdateRecipeSteps, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BulkUpdateRecipeStepsBatchResults{br, len(arg), false}
}

func (b *BulkUpdateRecipeStepsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BulkUpdateRecipeStepsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
