// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForBulkInsertRecipeIngredients implements pgx.CopyFromSource.
type iteratorForBulkInsertRecipeIngredients struct {
	rows                 []BulkInsertRecipeIngredientsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertRecipeIngredients) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertRecipeIngredients) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RecipeID,
		r.rows[0].Quantity,
		r.rows[0].Unit,
		r.rows[0].Name,
		r.rows[0].ImageUrl,
	}, nil
}

func (r iteratorForBulkInsertRecipeIngredients) Err() error {
	return nil
}

func (q *Queries) BulkInsertRecipeIngredients(ctx context.Context, arg []BulkInsertRecipeIngredientsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"recipe_ingredients"}, []string{"recipe_id", "quantity", "unit", "name", "image_url"}, &iteratorForBulkInsertRecipeIngredients{rows: arg})
}

// iteratorForBulkInsertRecipeSteps implements pgx.CopyFromSource.
type iteratorForBulkInsertRecipeSteps struct {
	rows                 []BulkInsertRecipeStepsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertRecipeSteps) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertRecipeSteps) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RecipeID,
		r.rows[0].Instruction,
		r.rows[0].ImageUrl,
		r.rows[0].StepNumber,
	}, nil
}

func (r iteratorForBulkInsertRecipeSteps) Err() error {
	return nil
}

func (q *Queries) BulkInsertRecipeSteps(ctx context.Context, arg []BulkInsertRecipeStepsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"recipe_steps"}, []string{"recipe_id", "instruction", "image_url", "step_number"}, &iteratorForBulkInsertRecipeSteps{rows: arg})
}
