// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type TimeUnit string

const (
	TimeUnitMinutes TimeUnit = "minutes"
	TimeUnitHours   TimeUnit = "hours"
	TimeUnitDays    TimeUnit = "days"
)

func (e *TimeUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeUnit(s)
	case string:
		*e = TimeUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeUnit: %T", src)
	}
	return nil
}

type NullTimeUnit struct {
	TimeUnit TimeUnit
	Valid    bool // Valid is true if TimeUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeUnit) Scan(value interface{}) error {
	if value == nil {
		ns.TimeUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeUnit), nil
}

type InvitationCode struct {
	ID        int64
	CodeHash  string
	InvitedBy pgtype.Int8
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Preference struct {
	ID                int32
	AllowPublicSignup bool
}

type Recipe struct {
	ID             int64
	UserID         pgtype.Int8
	ImageKey       pgtype.Text
	Title          string
	Description    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Published      bool
	CookTimeAmount pgtype.Int4
	CookTimeUnit   NullTimeUnit
	PrepTimeAmount pgtype.Int4
	PrepTimeUnit   NullTimeUnit
	Servings       pgtype.Float4
}

type RecipeIngredient struct {
	ID          int64
	RecipeID    int64
	Description pgtype.Text
	ImageKey    pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RecipeStep struct {
	ID          int64
	RecipeID    int64
	StepNumber  int32
	Instruction pgtype.Text
	ImageKey    pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID                    int64
	Email                 string
	FirstName             string
	LastName              string
	Role                  Role
	PasswordHash          string
	RefreshTokenHash      pgtype.Text
	RefreshTokenExpiresAt pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ValidInvitationCode struct {
	ID        int64
	CodeHash  string
	InvitedBy pgtype.Int8
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}
