// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkInsertRecipeIngredients(ctx context.Context, arg []BulkInsertRecipeIngredientsParams) (int64, error)
	BulkInsertRecipeSteps(ctx context.Context, arg []BulkInsertRecipeStepsParams) (int64, error)
	BulkUpdateRecipeIngredients(ctx context.Context, arg []BulkUpdateRecipeIngredientsParams) *BulkUpdateRecipeIngredientsBatchResults
	BulkUpdateRecipeSteps(ctx context.Context, arg []BulkUpdateRecipeStepsParams) *BulkUpdateRecipeStepsBatchResults
	CheckRecipeOwnership(ctx context.Context, arg CheckRecipeOwnershipParams) (bool, error)
	CheckUsersTableExists(ctx context.Context) (bool, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (int64, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (int64, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (int64, error)
	CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteRecipe(ctx context.Context, id int64) error
	DeleteRecipeIngredient(ctx context.Context, id int64) error
	DeleteRecipeIngredientsByIDs(ctx context.Context, arg DeleteRecipeIngredientsByIDsParams) error
	DeleteRecipeStep(ctx context.Context, id int64) error
	DeleteRecipeStepsByIDs(ctx context.Context, arg DeleteRecipeStepsByIDsParams) error
	GetAdminCount(ctx context.Context) (int64, error)
	GetPublishedRecipeAndOwner(ctx context.Context, id int64) (GetPublishedRecipeAndOwnerRow, error)
	GetRecipeAndOwner(ctx context.Context, id int64) (GetRecipeAndOwnerRow, error)
	GetRecipeIngredientExistence(ctx context.Context, id int64) (bool, error)
	GetRecipeIngredientIDs(ctx context.Context, recipeID int64) ([]int64, error)
	GetRecipeIngredientImageURL(ctx context.Context, id int64) (pgtype.Text, error)
	GetRecipeIngredients(ctx context.Context, recipeID int64) ([]RecipeIngredient, error)
	GetRecipeOwner(ctx context.Context, id int64) (pgtype.Int8, error)
	GetRecipeStepExistence(ctx context.Context, id int64) (bool, error)
	GetRecipeStepIDs(ctx context.Context, recipeID int64) ([]int64, error)
	GetRecipeStepImageURL(ctx context.Context, id int64) (pgtype.Text, error)
	GetRecipeSteps(ctx context.Context, recipeID int64) ([]RecipeStep, error)
	GetRecipesByOwner(ctx context.Context, id int64) ([]GetRecipesByOwnerRow, error)
	GetUser(ctx context.Context, lower string) (GetUserRow, error)
	GetUserRefreshTokenHash(ctx context.Context, id int64) (GetUserRefreshTokenHashRow, error)
	GetUserRole(ctx context.Context, id int64) (Role, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) error
	UpdateRecipeCoverImage(ctx context.Context, arg UpdateRecipeCoverImageParams) error
	UpdateRecipeIngredient(ctx context.Context, arg UpdateRecipeIngredientParams) error
	UpdateRecipeIngredientImage(ctx context.Context, arg UpdateRecipeIngredientImageParams) error
	UpdateRecipeStep(ctx context.Context, arg UpdateRecipeStepParams) error
	UpdateRecipeStepImage(ctx context.Context, arg UpdateRecipeStepImageParams) error
	UpdateUserRefreshTokenHash(ctx context.Context, arg UpdateUserRefreshTokenHashParams) error
}

var _ Querier = (*Queries)(nil)
