// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
)

const checkUsersTableExists = `-- name: CheckUsersTableExists :one
SELECT EXISTS (
	SELECT 1
	FROM information_schema.tables
	WHERE table_schema = 'public'
		AND table_name = 'users'
)
`

func (q *Queries) CheckUsersTableExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsersTableExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
