// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
)

const helloWorld = `-- name: HelloWorld :exec
SELECT 'hello world'
`

func (q *Queries) HelloWorld(ctx context.Context) error {
	_, err := q.db.Exec(ctx, helloWorld)
	return err
}
