// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchUpdateRecipeIngredientImages(ctx context.Context, arg []BatchUpdateRecipeIngredientImagesParams) *BatchUpdateRecipeIngredientImagesBatchResults
	BatchUpdateRecipeStepImages(ctx context.Context, arg []BatchUpdateRecipeStepImagesParams) *BatchUpdateRecipeStepImagesBatchResults
	BulkInsertRecipeIngredients(ctx context.Context, arg []BulkInsertRecipeIngredientsParams) (int64, error)
	BulkInsertRecipeSteps(ctx context.Context, arg []BulkInsertRecipeStepsParams) (int64, error)
	BulkUpdateRecipeIngredients(ctx context.Context, arg []BulkUpdateRecipeIngredientsParams) *BulkUpdateRecipeIngredientsBatchResults
	BulkUpdateRecipeSteps(ctx context.Context, arg []BulkUpdateRecipeStepsParams) *BulkUpdateRecipeStepsBatchResults
	CheckIngredientOwnership(ctx context.Context, arg CheckIngredientOwnershipParams) (bool, error)
	CheckRecipeOwnership(ctx context.Context, arg CheckRecipeOwnershipParams) (bool, error)
	CheckStepOwnership(ctx context.Context, arg CheckStepOwnershipParams) (bool, error)
	CheckUsersTableExists(ctx context.Context) (bool, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (int64, error)
	CreateEmptyRecipeIngredient(ctx context.Context, recipeID int64) (RecipeIngredient, error)
	CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) (int64, error)
	CreatePreferences(ctx context.Context, id int32) error
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (int64, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (int64, error)
	CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (CreateRecipeStepRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteRecipe(ctx context.Context, id int64) error
	DeleteRecipeIngredient(ctx context.Context, id int64) error
	DeleteRecipeIngredientImageKey(ctx context.Context, id int64) error
	DeleteRecipeIngredientsByIDs(ctx context.Context, arg DeleteRecipeIngredientsByIDsParams) error
	DeleteRecipeStep(ctx context.Context, id int64) error
	DeleteRecipeStepImageKey(ctx context.Context, id int64) error
	DeleteRecipeStepsByIDs(ctx context.Context, arg DeleteRecipeStepsByIDsParams) error
	DeleteUser(ctx context.Context, id int64) (int64, error)
	GetAdminCount(ctx context.Context) (int64, error)
	GetAllowPublicSignupPreference(ctx context.Context, id int32) (bool, error)
	GetInvitationCode(ctx context.Context, id int64) (string, error)
	GetPreferences(ctx context.Context, id int32) (Preference, error)
	GetPublicRecipes(ctx context.Context) ([]GetPublicRecipesRow, error)
	GetPublishedRecipeAndOwner(ctx context.Context, id int64) (GetPublishedRecipeAndOwnerRow, error)
	GetRecipeAndOwner(ctx context.Context, id int64) (GetRecipeAndOwnerRow, error)
	GetRecipeImageKey(ctx context.Context, id int64) (pgtype.Text, error)
	GetRecipeIngredientExistence(ctx context.Context, id int64) (bool, error)
	GetRecipeIngredientIDs(ctx context.Context, recipeID int64) ([]int64, error)
	GetRecipeIngredientImageKey(ctx context.Context, id int64) (pgtype.Text, error)
	GetRecipeIngredients(ctx context.Context, recipeID int64) ([]RecipeIngredient, error)
	GetRecipeOwner(ctx context.Context, id int64) (pgtype.Int8, error)
	GetRecipeStepExistence(ctx context.Context, id int64) (bool, error)
	GetRecipeStepIDs(ctx context.Context, recipeID int64) ([]int64, error)
	GetRecipeStepImageKey(ctx context.Context, id int64) (pgtype.Text, error)
	GetRecipeSteps(ctx context.Context, recipeID int64) ([]RecipeStep, error)
	GetRecipesByOwner(ctx context.Context, id int64) ([]GetRecipesByOwnerRow, error)
	GetUser(ctx context.Context, lower string) (GetUserRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	GetUserPasswordHash(ctx context.Context, id int64) (string, error)
	GetUserRecipeImages(ctx context.Context, userID pgtype.Int8) ([]pgtype.Text, error)
	GetUserRecipeIngredientImages(ctx context.Context, userID pgtype.Int8) ([]pgtype.Text, error)
	GetUserRecipeStepImages(ctx context.Context, userID pgtype.Int8) ([]pgtype.Text, error)
	GetUserRefreshTokenHash(ctx context.Context, id int64) (GetUserRefreshTokenHashRow, error)
	GetUserRole(ctx context.Context, id int64) (Role, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	RedeemInvitationCode(ctx context.Context, id int64) (int64, error)
	UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (Preference, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (UpdateRecipeRow, error)
	UpdateRecipeCoverImage(ctx context.Context, arg UpdateRecipeCoverImageParams) error
	UpdateRecipeIngredient(ctx context.Context, arg UpdateRecipeIngredientParams) (RecipeIngredient, error)
	UpdateRecipeIngredientImage(ctx context.Context, arg UpdateRecipeIngredientImageParams) error
	UpdateRecipeStep(ctx context.Context, arg UpdateRecipeStepParams) (UpdateRecipeStepRow, error)
	UpdateRecipeStepImage(ctx context.Context, arg UpdateRecipeStepImageParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserRefreshTokenHash(ctx context.Context, arg UpdateUserRefreshTokenHashParams) error
}

var _ Querier = (*Queries)(nil)
