// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/querier.go -destination internal/dbmock/dbmock.go -package dbmock
//

// Package dbmock is a generated GoMock package.
package dbmock

import (
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	database "github.com/matt-dz/wecook/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// BatchUpdateRecipeIngredientImages mocks base method.
func (m *MockQuerier) BatchUpdateRecipeIngredientImages(ctx context.Context, arg []database.BatchUpdateRecipeIngredientImagesParams) *database.BatchUpdateRecipeIngredientImagesBatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateRecipeIngredientImages", ctx, arg)
	ret0, _ := ret[0].(*database.BatchUpdateRecipeIngredientImagesBatchResults)
	return ret0
}

// BatchUpdateRecipeIngredientImages indicates an expected call of BatchUpdateRecipeIngredientImages.
func (mr *MockQuerierMockRecorder) BatchUpdateRecipeIngredientImages(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateRecipeIngredientImages", reflect.TypeOf((*MockQuerier)(nil).BatchUpdateRecipeIngredientImages), ctx, arg)
}

// BatchUpdateRecipeStepImages mocks base method.
func (m *MockQuerier) BatchUpdateRecipeStepImages(ctx context.Context, arg []database.BatchUpdateRecipeStepImagesParams) *database.BatchUpdateRecipeStepImagesBatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateRecipeStepImages", ctx, arg)
	ret0, _ := ret[0].(*database.BatchUpdateRecipeStepImagesBatchResults)
	return ret0
}

// BatchUpdateRecipeStepImages indicates an expected call of BatchUpdateRecipeStepImages.
func (mr *MockQuerierMockRecorder) BatchUpdateRecipeStepImages(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateRecipeStepImages", reflect.TypeOf((*MockQuerier)(nil).BatchUpdateRecipeStepImages), ctx, arg)
}

// BulkInsertRecipeIngredients mocks base method.
func (m *MockQuerier) BulkInsertRecipeIngredients(ctx context.Context, arg []database.BulkInsertRecipeIngredientsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertRecipeIngredients", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkInsertRecipeIngredients indicates an expected call of BulkInsertRecipeIngredients.
func (mr *MockQuerierMockRecorder) BulkInsertRecipeIngredients(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertRecipeIngredients", reflect.TypeOf((*MockQuerier)(nil).BulkInsertRecipeIngredients), ctx, arg)
}

// BulkInsertRecipeSteps mocks base method.
func (m *MockQuerier) BulkInsertRecipeSteps(ctx context.Context, arg []database.BulkInsertRecipeStepsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertRecipeSteps", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkInsertRecipeSteps indicates an expected call of BulkInsertRecipeSteps.
func (mr *MockQuerierMockRecorder) BulkInsertRecipeSteps(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertRecipeSteps", reflect.TypeOf((*MockQuerier)(nil).BulkInsertRecipeSteps), ctx, arg)
}

// BulkUpdateRecipeIngredients mocks base method.
func (m *MockQuerier) BulkUpdateRecipeIngredients(ctx context.Context, arg []database.BulkUpdateRecipeIngredientsParams) *database.BulkUpdateRecipeIngredientsBatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRecipeIngredients", ctx, arg)
	ret0, _ := ret[0].(*database.BulkUpdateRecipeIngredientsBatchResults)
	return ret0
}

// BulkUpdateRecipeIngredients indicates an expected call of BulkUpdateRecipeIngredients.
func (mr *MockQuerierMockRecorder) BulkUpdateRecipeIngredients(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRecipeIngredients", reflect.TypeOf((*MockQuerier)(nil).BulkUpdateRecipeIngredients), ctx, arg)
}

// BulkUpdateRecipeSteps mocks base method.
func (m *MockQuerier) BulkUpdateRecipeSteps(ctx context.Context, arg []database.BulkUpdateRecipeStepsParams) *database.BulkUpdateRecipeStepsBatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRecipeSteps", ctx, arg)
	ret0, _ := ret[0].(*database.BulkUpdateRecipeStepsBatchResults)
	return ret0
}

// BulkUpdateRecipeSteps indicates an expected call of BulkUpdateRecipeSteps.
func (mr *MockQuerierMockRecorder) BulkUpdateRecipeSteps(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRecipeSteps", reflect.TypeOf((*MockQuerier)(nil).BulkUpdateRecipeSteps), ctx, arg)
}

// CheckIngredientOwnership mocks base method.
func (m *MockQuerier) CheckIngredientOwnership(ctx context.Context, arg database.CheckIngredientOwnershipParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIngredientOwnership", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIngredientOwnership indicates an expected call of CheckIngredientOwnership.
func (mr *MockQuerierMockRecorder) CheckIngredientOwnership(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIngredientOwnership", reflect.TypeOf((*MockQuerier)(nil).CheckIngredientOwnership), ctx, arg)
}

// CheckRecipeOwnership mocks base method.
func (m *MockQuerier) CheckRecipeOwnership(ctx context.Context, arg database.CheckRecipeOwnershipParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRecipeOwnership", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRecipeOwnership indicates an expected call of CheckRecipeOwnership.
func (mr *MockQuerierMockRecorder) CheckRecipeOwnership(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRecipeOwnership", reflect.TypeOf((*MockQuerier)(nil).CheckRecipeOwnership), ctx, arg)
}

// CheckStepOwnership mocks base method.
func (m *MockQuerier) CheckStepOwnership(ctx context.Context, arg database.CheckStepOwnershipParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStepOwnership", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStepOwnership indicates an expected call of CheckStepOwnership.
func (mr *MockQuerierMockRecorder) CheckStepOwnership(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStepOwnership", reflect.TypeOf((*MockQuerier)(nil).CheckStepOwnership), ctx, arg)
}

// CheckUsersTableExists mocks base method.
func (m *MockQuerier) CheckUsersTableExists(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsersTableExists", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUsersTableExists indicates an expected call of CheckUsersTableExists.
func (mr *MockQuerierMockRecorder) CheckUsersTableExists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsersTableExists", reflect.TypeOf((*MockQuerier)(nil).CheckUsersTableExists), ctx)
}

// CreateAdmin mocks base method.
func (m *MockQuerier) CreateAdmin(ctx context.Context, arg database.CreateAdminParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdmin", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdmin indicates an expected call of CreateAdmin.
func (mr *MockQuerierMockRecorder) CreateAdmin(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdmin", reflect.TypeOf((*MockQuerier)(nil).CreateAdmin), ctx, arg)
}

// CreateEmptyRecipeIngredient mocks base method.
func (m *MockQuerier) CreateEmptyRecipeIngredient(ctx context.Context, recipeID int64) (database.RecipeIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmptyRecipeIngredient", ctx, recipeID)
	ret0, _ := ret[0].(database.RecipeIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmptyRecipeIngredient indicates an expected call of CreateEmptyRecipeIngredient.
func (mr *MockQuerierMockRecorder) CreateEmptyRecipeIngredient(ctx, recipeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmptyRecipeIngredient", reflect.TypeOf((*MockQuerier)(nil).CreateEmptyRecipeIngredient), ctx, recipeID)
}

// CreateRecipe mocks base method.
func (m *MockQuerier) CreateRecipe(ctx context.Context, arg database.CreateRecipeParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecipe", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecipe indicates an expected call of CreateRecipe.
func (mr *MockQuerierMockRecorder) CreateRecipe(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecipe", reflect.TypeOf((*MockQuerier)(nil).CreateRecipe), ctx, arg)
}

// CreateRecipeIngredient mocks base method.
func (m *MockQuerier) CreateRecipeIngredient(ctx context.Context, arg database.CreateRecipeIngredientParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecipeIngredient", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecipeIngredient indicates an expected call of CreateRecipeIngredient.
func (mr *MockQuerierMockRecorder) CreateRecipeIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecipeIngredient", reflect.TypeOf((*MockQuerier)(nil).CreateRecipeIngredient), ctx, arg)
}

// CreateRecipeStep mocks base method.
func (m *MockQuerier) CreateRecipeStep(ctx context.Context, arg database.CreateRecipeStepParams) (database.CreateRecipeStepRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecipeStep", ctx, arg)
	ret0, _ := ret[0].(database.CreateRecipeStepRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecipeStep indicates an expected call of CreateRecipeStep.
func (mr *MockQuerierMockRecorder) CreateRecipeStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecipeStep", reflect.TypeOf((*MockQuerier)(nil).CreateRecipeStep), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg database.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// DeleteRecipe mocks base method.
func (m *MockQuerier) DeleteRecipe(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipe", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipe indicates an expected call of DeleteRecipe.
func (mr *MockQuerierMockRecorder) DeleteRecipe(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipe", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipe), ctx, id)
}

// DeleteRecipeIngredient mocks base method.
func (m *MockQuerier) DeleteRecipeIngredient(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipeIngredient", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipeIngredient indicates an expected call of DeleteRecipeIngredient.
func (mr *MockQuerierMockRecorder) DeleteRecipeIngredient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipeIngredient", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipeIngredient), ctx, id)
}

// DeleteRecipeIngredientImageURL mocks base method.
func (m *MockQuerier) DeleteRecipeIngredientImageURL(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipeIngredientImageURL", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipeIngredientImageURL indicates an expected call of DeleteRecipeIngredientImageURL.
func (mr *MockQuerierMockRecorder) DeleteRecipeIngredientImageURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipeIngredientImageURL", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipeIngredientImageURL), ctx, id)
}

// DeleteRecipeIngredientsByIDs mocks base method.
func (m *MockQuerier) DeleteRecipeIngredientsByIDs(ctx context.Context, arg database.DeleteRecipeIngredientsByIDsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipeIngredientsByIDs", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipeIngredientsByIDs indicates an expected call of DeleteRecipeIngredientsByIDs.
func (mr *MockQuerierMockRecorder) DeleteRecipeIngredientsByIDs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipeIngredientsByIDs", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipeIngredientsByIDs), ctx, arg)
}

// DeleteRecipeStep mocks base method.
func (m *MockQuerier) DeleteRecipeStep(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipeStep", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipeStep indicates an expected call of DeleteRecipeStep.
func (mr *MockQuerierMockRecorder) DeleteRecipeStep(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipeStep", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipeStep), ctx, id)
}

// DeleteRecipeStepImageURL mocks base method.
func (m *MockQuerier) DeleteRecipeStepImageURL(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipeStepImageURL", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipeStepImageURL indicates an expected call of DeleteRecipeStepImageURL.
func (mr *MockQuerierMockRecorder) DeleteRecipeStepImageURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipeStepImageURL", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipeStepImageURL), ctx, id)
}

// DeleteRecipeStepsByIDs mocks base method.
func (m *MockQuerier) DeleteRecipeStepsByIDs(ctx context.Context, arg database.DeleteRecipeStepsByIDsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipeStepsByIDs", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipeStepsByIDs indicates an expected call of DeleteRecipeStepsByIDs.
func (mr *MockQuerierMockRecorder) DeleteRecipeStepsByIDs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipeStepsByIDs", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipeStepsByIDs), ctx, arg)
}

// GetAdminCount mocks base method.
func (m *MockQuerier) GetAdminCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminCount indicates an expected call of GetAdminCount.
func (mr *MockQuerierMockRecorder) GetAdminCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminCount", reflect.TypeOf((*MockQuerier)(nil).GetAdminCount), ctx)
}

// GetPublishedRecipeAndOwner mocks base method.
func (m *MockQuerier) GetPublishedRecipeAndOwner(ctx context.Context, id int64) (database.GetPublishedRecipeAndOwnerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedRecipeAndOwner", ctx, id)
	ret0, _ := ret[0].(database.GetPublishedRecipeAndOwnerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedRecipeAndOwner indicates an expected call of GetPublishedRecipeAndOwner.
func (mr *MockQuerierMockRecorder) GetPublishedRecipeAndOwner(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedRecipeAndOwner", reflect.TypeOf((*MockQuerier)(nil).GetPublishedRecipeAndOwner), ctx, id)
}

// GetRecipeAndOwner mocks base method.
func (m *MockQuerier) GetRecipeAndOwner(ctx context.Context, id int64) (database.GetRecipeAndOwnerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeAndOwner", ctx, id)
	ret0, _ := ret[0].(database.GetRecipeAndOwnerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeAndOwner indicates an expected call of GetRecipeAndOwner.
func (mr *MockQuerierMockRecorder) GetRecipeAndOwner(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeAndOwner", reflect.TypeOf((*MockQuerier)(nil).GetRecipeAndOwner), ctx, id)
}

// GetRecipeIngredientExistence mocks base method.
func (m *MockQuerier) GetRecipeIngredientExistence(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeIngredientExistence", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeIngredientExistence indicates an expected call of GetRecipeIngredientExistence.
func (mr *MockQuerierMockRecorder) GetRecipeIngredientExistence(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeIngredientExistence", reflect.TypeOf((*MockQuerier)(nil).GetRecipeIngredientExistence), ctx, id)
}

// GetRecipeIngredientIDs mocks base method.
func (m *MockQuerier) GetRecipeIngredientIDs(ctx context.Context, recipeID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeIngredientIDs", ctx, recipeID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeIngredientIDs indicates an expected call of GetRecipeIngredientIDs.
func (mr *MockQuerierMockRecorder) GetRecipeIngredientIDs(ctx, recipeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeIngredientIDs", reflect.TypeOf((*MockQuerier)(nil).GetRecipeIngredientIDs), ctx, recipeID)
}

// GetRecipeIngredientImageURL mocks base method.
func (m *MockQuerier) GetRecipeIngredientImageURL(ctx context.Context, id int64) (pgtype.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeIngredientImageURL", ctx, id)
	ret0, _ := ret[0].(pgtype.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeIngredientImageURL indicates an expected call of GetRecipeIngredientImageURL.
func (mr *MockQuerierMockRecorder) GetRecipeIngredientImageURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeIngredientImageURL", reflect.TypeOf((*MockQuerier)(nil).GetRecipeIngredientImageURL), ctx, id)
}

// GetRecipeIngredients mocks base method.
func (m *MockQuerier) GetRecipeIngredients(ctx context.Context, recipeID int64) ([]database.RecipeIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeIngredients", ctx, recipeID)
	ret0, _ := ret[0].([]database.RecipeIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeIngredients indicates an expected call of GetRecipeIngredients.
func (mr *MockQuerierMockRecorder) GetRecipeIngredients(ctx, recipeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeIngredients", reflect.TypeOf((*MockQuerier)(nil).GetRecipeIngredients), ctx, recipeID)
}

// GetRecipeOwner mocks base method.
func (m *MockQuerier) GetRecipeOwner(ctx context.Context, id int64) (pgtype.Int8, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeOwner", ctx, id)
	ret0, _ := ret[0].(pgtype.Int8)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeOwner indicates an expected call of GetRecipeOwner.
func (mr *MockQuerierMockRecorder) GetRecipeOwner(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeOwner", reflect.TypeOf((*MockQuerier)(nil).GetRecipeOwner), ctx, id)
}

// GetRecipeStepExistence mocks base method.
func (m *MockQuerier) GetRecipeStepExistence(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeStepExistence", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeStepExistence indicates an expected call of GetRecipeStepExistence.
func (mr *MockQuerierMockRecorder) GetRecipeStepExistence(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeStepExistence", reflect.TypeOf((*MockQuerier)(nil).GetRecipeStepExistence), ctx, id)
}

// GetRecipeStepIDs mocks base method.
func (m *MockQuerier) GetRecipeStepIDs(ctx context.Context, recipeID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeStepIDs", ctx, recipeID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeStepIDs indicates an expected call of GetRecipeStepIDs.
func (mr *MockQuerierMockRecorder) GetRecipeStepIDs(ctx, recipeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeStepIDs", reflect.TypeOf((*MockQuerier)(nil).GetRecipeStepIDs), ctx, recipeID)
}

// GetRecipeStepImageURL mocks base method.
func (m *MockQuerier) GetRecipeStepImageURL(ctx context.Context, id int64) (pgtype.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeStepImageURL", ctx, id)
	ret0, _ := ret[0].(pgtype.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeStepImageURL indicates an expected call of GetRecipeStepImageURL.
func (mr *MockQuerierMockRecorder) GetRecipeStepImageURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeStepImageURL", reflect.TypeOf((*MockQuerier)(nil).GetRecipeStepImageURL), ctx, id)
}

// GetRecipeSteps mocks base method.
func (m *MockQuerier) GetRecipeSteps(ctx context.Context, recipeID int64) ([]database.RecipeStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeSteps", ctx, recipeID)
	ret0, _ := ret[0].([]database.RecipeStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeSteps indicates an expected call of GetRecipeSteps.
func (mr *MockQuerierMockRecorder) GetRecipeSteps(ctx, recipeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeSteps", reflect.TypeOf((*MockQuerier)(nil).GetRecipeSteps), ctx, recipeID)
}

// GetRecipesByOwner mocks base method.
func (m *MockQuerier) GetRecipesByOwner(ctx context.Context, id int64) ([]database.GetRecipesByOwnerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipesByOwner", ctx, id)
	ret0, _ := ret[0].([]database.GetRecipesByOwnerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipesByOwner indicates an expected call of GetRecipesByOwner.
func (mr *MockQuerierMockRecorder) GetRecipesByOwner(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipesByOwner", reflect.TypeOf((*MockQuerier)(nil).GetRecipesByOwner), ctx, id)
}

// GetUser mocks base method.
func (m *MockQuerier) GetUser(ctx context.Context, lower string) (database.GetUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, lower)
	ret0, _ := ret[0].(database.GetUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockQuerierMockRecorder) GetUser(ctx, lower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockQuerier)(nil).GetUser), ctx, lower)
}

// GetUserRefreshTokenHash mocks base method.
func (m *MockQuerier) GetUserRefreshTokenHash(ctx context.Context, id int64) (database.GetUserRefreshTokenHashRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRefreshTokenHash", ctx, id)
	ret0, _ := ret[0].(database.GetUserRefreshTokenHashRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRefreshTokenHash indicates an expected call of GetUserRefreshTokenHash.
func (mr *MockQuerierMockRecorder) GetUserRefreshTokenHash(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRefreshTokenHash", reflect.TypeOf((*MockQuerier)(nil).GetUserRefreshTokenHash), ctx, id)
}

// GetUserRole mocks base method.
func (m *MockQuerier) GetUserRole(ctx context.Context, id int64) (database.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, id)
	ret0, _ := ret[0].(database.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockQuerierMockRecorder) GetUserRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockQuerier)(nil).GetUserRole), ctx, id)
}

// UpdateRecipe mocks base method.
func (m *MockQuerier) UpdateRecipe(ctx context.Context, arg database.UpdateRecipeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecipe", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecipe indicates an expected call of UpdateRecipe.
func (mr *MockQuerierMockRecorder) UpdateRecipe(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecipe", reflect.TypeOf((*MockQuerier)(nil).UpdateRecipe), ctx, arg)
}

// UpdateRecipeCoverImage mocks base method.
func (m *MockQuerier) UpdateRecipeCoverImage(ctx context.Context, arg database.UpdateRecipeCoverImageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecipeCoverImage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecipeCoverImage indicates an expected call of UpdateRecipeCoverImage.
func (mr *MockQuerierMockRecorder) UpdateRecipeCoverImage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecipeCoverImage", reflect.TypeOf((*MockQuerier)(nil).UpdateRecipeCoverImage), ctx, arg)
}

// UpdateRecipeIngredient mocks base method.
func (m *MockQuerier) UpdateRecipeIngredient(ctx context.Context, arg database.UpdateRecipeIngredientParams) (database.RecipeIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecipeIngredient", ctx, arg)
	ret0, _ := ret[0].(database.RecipeIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecipeIngredient indicates an expected call of UpdateRecipeIngredient.
func (mr *MockQuerierMockRecorder) UpdateRecipeIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecipeIngredient", reflect.TypeOf((*MockQuerier)(nil).UpdateRecipeIngredient), ctx, arg)
}

// UpdateRecipeIngredientImage mocks base method.
func (m *MockQuerier) UpdateRecipeIngredientImage(ctx context.Context, arg database.UpdateRecipeIngredientImageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecipeIngredientImage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecipeIngredientImage indicates an expected call of UpdateRecipeIngredientImage.
func (mr *MockQuerierMockRecorder) UpdateRecipeIngredientImage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecipeIngredientImage", reflect.TypeOf((*MockQuerier)(nil).UpdateRecipeIngredientImage), ctx, arg)
}

// UpdateRecipeStep mocks base method.
func (m *MockQuerier) UpdateRecipeStep(ctx context.Context, arg database.UpdateRecipeStepParams) (database.UpdateRecipeStepRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecipeStep", ctx, arg)
	ret0, _ := ret[0].(database.UpdateRecipeStepRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecipeStep indicates an expected call of UpdateRecipeStep.
func (mr *MockQuerierMockRecorder) UpdateRecipeStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecipeStep", reflect.TypeOf((*MockQuerier)(nil).UpdateRecipeStep), ctx, arg)
}

// UpdateRecipeStepImage mocks base method.
func (m *MockQuerier) UpdateRecipeStepImage(ctx context.Context, arg database.UpdateRecipeStepImageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecipeStepImage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecipeStepImage indicates an expected call of UpdateRecipeStepImage.
func (mr *MockQuerierMockRecorder) UpdateRecipeStepImage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecipeStepImage", reflect.TypeOf((*MockQuerier)(nil).UpdateRecipeStepImage), ctx, arg)
}

// UpdateUserRefreshTokenHash mocks base method.
func (m *MockQuerier) UpdateUserRefreshTokenHash(ctx context.Context, arg database.UpdateUserRefreshTokenHashParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRefreshTokenHash", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRefreshTokenHash indicates an expected call of UpdateUserRefreshTokenHash.
func (mr *MockQuerierMockRecorder) UpdateUserRefreshTokenHash(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRefreshTokenHash", reflect.TypeOf((*MockQuerier)(nil).UpdateUserRefreshTokenHash), ctx, arg)
}
