// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create an admin.",
                "parameters": [
                    {
                        "description": "Create Admin Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes_admin.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes_admin.CreateAdminResponse"
                        }
                    },
                    "409": {
                        "description": "Status Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    }
                }
            }
        },
        "/api/admin/user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create a user.",
                "parameters": [
                    {
                        "description": "Create User Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes_users.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes_users.CreateUserResponse"
                        }
                    },
                    "409": {
                        "description": "Status Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User login.",
                "parameters": [
                    {
                        "description": "User Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes_users.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "tags": [
                    "Ping"
                ],
                "summary": "Ping endpoint.",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/session": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Refresh user session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cookie header: refresh_token=...",
                        "name": "Cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    }
                }
            }
        },
        "/api/setup/admin": {
            "post": {
                "description": "This endpoint should only be hit once on system startup.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Setup the first admin.",
                "parameters": [
                    {
                        "description": "Create Admin Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes_admin.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_routes_admin.CreateAdminResponse"
                        }
                    },
                    "409": {
                        "description": "Status Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_matt-dz_wecook_internal_api_error.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_matt-dz_wecook_internal_api_error.Error": {
            "description": "Standard error response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "internal_api_routes_admin.CreateAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_api_routes_admin.CreateAdminResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api_routes_users.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_api_routes_users.CreateUserResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api_routes_users.UserLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WeCook API",
	Description:      "API Server for the WeCook application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
