// Code generated by MockGen. DO NOT EDIT.
// Source: internal/filestore/filestore.go
//
// Generated by this command:
//
//	mockgen -source=internal/filestore/filestore.go -destination internal/filestore/filestoremock.go -package filestore
//

// Package filestore is a generated GoMock package.
package filestore

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStoreInterface is a mock of FileStoreInterface interface.
type MockFileStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockFileStoreInterfaceMockRecorder is the mock recorder for MockFileStoreInterface.
type MockFileStoreInterfaceMockRecorder struct {
	mock *MockFileStoreInterface
}

// NewMockFileStoreInterface creates a new mock instance.
func NewMockFileStoreInterface(ctrl *gomock.Controller) *MockFileStoreInterface {
	mock := &MockFileStoreInterface{ctrl: ctrl}
	mock.recorder = &MockFileStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStoreInterface) EXPECT() *MockFileStoreInterfaceMockRecorder {
	return m.recorder
}

// DeleteKey mocks base method.
func (m *MockFileStoreInterface) DeleteKey(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockFileStoreInterfaceMockRecorder) DeleteKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKey", reflect.TypeOf((*MockFileStoreInterface)(nil).DeleteKey), key)
}

// FileURL mocks base method.
func (m *MockFileStoreInterface) FileURL(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileURL", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// FileURL indicates an expected call of FileURL.
func (mr *MockFileStoreInterfaceMockRecorder) FileURL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileURL", reflect.TypeOf((*MockFileStoreInterface)(nil).FileURL), key)
}

// WriteIngredientImage mocks base method.
func (m *MockFileStoreInterface) WriteIngredientImage(suffix string, data []byte) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteIngredientImage", suffix, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteIngredientImage indicates an expected call of WriteIngredientImage.
func (mr *MockFileStoreInterfaceMockRecorder) WriteIngredientImage(suffix, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteIngredientImage", reflect.TypeOf((*MockFileStoreInterface)(nil).WriteIngredientImage), suffix, data)
}

// WriteRecipeCoverImage mocks base method.
func (m *MockFileStoreInterface) WriteRecipeCoverImage(suffix string, data []byte) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteRecipeCoverImage", suffix, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteRecipeCoverImage indicates an expected call of WriteRecipeCoverImage.
func (mr *MockFileStoreInterfaceMockRecorder) WriteRecipeCoverImage(suffix, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteRecipeCoverImage", reflect.TypeOf((*MockFileStoreInterface)(nil).WriteRecipeCoverImage), suffix, data)
}

// WriteStepImage mocks base method.
func (m *MockFileStoreInterface) WriteStepImage(suffix string, data []byte) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteStepImage", suffix, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteStepImage indicates an expected call of WriteStepImage.
func (mr *MockFileStoreInterfaceMockRecorder) WriteStepImage(suffix, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteStepImage", reflect.TypeOf((*MockFileStoreInterface)(nil).WriteStepImage), suffix, data)
}
