// Code generated by MockGen. DO NOT EDIT.
// Source: internal/filestore/filestore.go
//
// Generated by this command:
//
//	mockgen -source=internal/filestore/filestore.go -destination internal/filestore/filestoremock.go -package filestore
//

// Package filestore is a generated GoMock package.
package filestore

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStoreInterface is a mock of FileStoreInterface interface.
type MockFileStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockFileStoreInterfaceMockRecorder is the mock recorder for MockFileStoreInterface.
type MockFileStoreInterfaceMockRecorder struct {
	mock *MockFileStoreInterface
}

// NewMockFileStoreInterface creates a new mock instance.
func NewMockFileStoreInterface(ctrl *gomock.Controller) *MockFileStoreInterface {
	mock := &MockFileStoreInterface{ctrl: ctrl}
	mock.recorder = &MockFileStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStoreInterface) EXPECT() *MockFileStoreInterfaceMockRecorder {
	return m.recorder
}

// DeleteURLPath mocks base method.
func (m *MockFileStoreInterface) DeleteURLPath(urlpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLPath", urlpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteURLPath indicates an expected call of DeleteURLPath.
func (mr *MockFileStoreInterfaceMockRecorder) DeleteURLPath(urlpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLPath", reflect.TypeOf((*MockFileStoreInterface)(nil).DeleteURLPath), urlpath)
}

// FileURL mocks base method.
func (m *MockFileStoreInterface) FileURL(host string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileURL", host)
	ret0, _ := ret[0].(string)
	return ret0
}

// FileURL indicates an expected call of FileURL.
func (mr *MockFileStoreInterfaceMockRecorder) FileURL(host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileURL", reflect.TypeOf((*MockFileStoreInterface)(nil).FileURL), host)
}

// WriteIngredientImage mocks base method.
func (m *MockFileStoreInterface) WriteIngredientImage(recipeID, ingredientID int64, suffix string, data []byte) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteIngredientImage", recipeID, ingredientID, suffix, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteIngredientImage indicates an expected call of WriteIngredientImage.
func (mr *MockFileStoreInterfaceMockRecorder) WriteIngredientImage(recipeID, ingredientID, suffix, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteIngredientImage", reflect.TypeOf((*MockFileStoreInterface)(nil).WriteIngredientImage), recipeID, ingredientID, suffix, data)
}

// WriteRecipeCoverImage mocks base method.
func (m *MockFileStoreInterface) WriteRecipeCoverImage(recipeID int64, suffix string, data []byte) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteRecipeCoverImage", recipeID, suffix, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteRecipeCoverImage indicates an expected call of WriteRecipeCoverImage.
func (mr *MockFileStoreInterfaceMockRecorder) WriteRecipeCoverImage(recipeID, suffix, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteRecipeCoverImage", reflect.TypeOf((*MockFileStoreInterface)(nil).WriteRecipeCoverImage), recipeID, suffix, data)
}

// WriteStepImage mocks base method.
func (m *MockFileStoreInterface) WriteStepImage(recipeID, stepID int64, suffix string, data []byte) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteStepImage", recipeID, stepID, suffix, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteStepImage indicates an expected call of WriteStepImage.
func (mr *MockFileStoreInterfaceMockRecorder) WriteStepImage(recipeID, stepID, suffix, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteStepImage", reflect.TypeOf((*MockFileStoreInterface)(nil).WriteStepImage), recipeID, stepID, suffix, data)
}
